language: python
python:
  - '2.7'
  - '3.6'
install: pip install -r requirements-testing.txt
dist: trusty
os: linux
script: coverage run --source=mnamer -m unittest discover -v
after_success:
  - codecov
